repos:
  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 0.50.0
    hooks:
      - id: pyrefly-check
        name: Pyrefly (type checking)
        pass_filenames: false
        additional_dependencies:
          - packaging==25.0
